---
- name: Destroy molecule instance
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Remove hyprland-skel container
      containers.podman.podman_container:
        name: hyprland-skel
        state: absent
